### ISSUE TITLE
Can't create docker image.

### ISSUE THREAD

**Issue by NoriSumi** [aws-samples/template-for-closed-network-system-workloads-on-aws#7]
I've encountered error issue in deploy procedures.
The messages from cdk is below, and seemed can't to be pull alpine packages.
I've tried to add nameserver(8.8.8.8) to /etc/resolv.conf written in DockerfileDNS, however same error appeared.
Has enyone entcounterd same issues?

--------error outputs written in below lines---------

 ---> Running in 5cd51315b5aa

fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz

fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.17/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.17/main: No such file or directory

ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.17/community: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.17/community: No such file or directory
2 errors; 37 distinct packages available

The command '/bin/sh -c apk update && apk add --upgrade sqlite-libs && apk add --upgrade libcrypto3 && apk add --upgrade libssl3 && apk add curl && apk add -f python3 py3-pip && pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 2

Error executing: cd ../batch && aws ecr get-login-password --region ap-northeast-1 --profile xxxxProfile | docker login --username AWS --password-stdin 617558323651.dkr.ecr.ap-northeast-1.amazonaws.com &&     docker build . -t templateapp-batch:latest &&     docker tag templateapp-batch 617558323651.dkr.ecr.ap-northeast-1.amazonaws.com/xxxxdevtemplateappbase-batchbatchrepository57090017-baiihfqwreel:latest &&     docker push 617558323651.dkr.ecr.ap-northeast-1.amazonaws.com/xxxxdevtemplateappbase-batchbatchrepository57090017-baiihfqwreel:latest
[10:16:36] 'buildBatch' errored after 14 s
[10:16:36] Error: 2
    at formatError (/root/aws/template-for-closed-network-system-workloads-on-aws/infra/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
    at Gulp.<anonymous> (/root/aws/template-for-closed-network-system-workloads-on-aws/infra/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (node:events:402:35)
    at Gulp.emit (node:domain:475:12)
    at Object.error (/root/aws/template-for-closed-network-system-workloads-on-aws/infra/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/root/aws/template-for-closed-network-system-workloads-on-aws/infra/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/root/aws/template-for-closed-network-system-workloads-on-aws/infra/node_modules/once/once.js:25:25)
    at f (/root/aws/template-for-closed-network-system-workloads-on-aws/infra/node_modules/once/once.js:25:25)
    at tryCatch (/root/aws/template-for-closed-network-system-workloads-on-aws/infra/node_modules/async-done/index.js:24:15)
    at done (/root/aws/template-for-closed-network-system-workloads-on-aws/infra/node_modules/async-done/index.js:40:12)
[10:16:36] 'deploy' errored after 54 s

**Comment by suzukyz** [comment]
@NoriSumi 
Thank you for creating issue.
But I've never met same issue before.

I found similar issue.
https://github.com/gliderlabs/docker-alpine/issues/386

In this issue, people suggested some solutions.
1. Add `8.8.8.8` to `/etc/resolve.conf` // It's a same that you did.
2. Restart `systemd-resolved` like this, `$ sudo service systemd-resolved restart` 
    ref: https://github.com/gliderlabs/docker-alpine/issues/386#issuecomment-842947269
3. Restart Docker daemon 
    ref:  https://github.com/gliderlabs/docker-alpine/issues/386#issuecomment-895475292
4. Restart your OS
    ref: https://github.com/gliderlabs/docker-alpine/issues/386#issuecomment-1481572209
5. Change alpine version to 3.12 or others (in below issue, people reported 3.12 worked.)
    ref: https://github.com/gliderlabs/docker-alpine/issues/386#issuecomment-975624613

Could you try above solutions and give me updates?

**Comment by NoriSumi** [comment]
Thank you for many advices. My mistake was forgot to stop firewalld serices that prevent outgoint DNS queries.
Issue was removed by the command "systemctl stop firewalld".
